name: Trigger auto deployment for wind-mill-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/wind-mill-app-AutoDeployTrigger-99602067-9e11-424e-86f7-57f479e6b001.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.WINDMILLAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WINDMILLAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WINDMILLAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: windmillacrkl2026.azurecr.io
          registryUsername: ${{ secrets.WINDMILLAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WINDMILLAPP_REGISTRY_PASSWORD }}
          containerAppName: wind-mill-app
          resourceGroup: wind-turbine-rg
          imageToBuild: windmillacrkl2026.azurecr.io/wind-mill-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


